# Generated by Django 5.0.7 on 2024-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('hidden', 'Hidden'), ('all', 'All'), ('top', 'Top')], default='all', max_length=25),
        ),
    ]
