# Generated by Django 5.0.7 on 2024-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_keyword_stocklist_news_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='sector',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
