# Generated by Django 5.0.7 on 2024-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_stocklist_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='country',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='index',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='instrument_type',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
